#
# taken from https://github.com/stefanberger/swtpm/wiki/Dockerfiles + customized for local needs
#
FROM ubuntu:20.04
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get -y update && \
    apt-get -y install build-essential fakeroot devscripts equivs

ADD . /build/swtpm
WORKDIR /build/swtpm
RUN dpkg -i /build/swtpm/build/libtpms/libtpms*.deb

RUN git clone https://github.com/stefanberger/swtpm.git
WORKDIR /build/swtpm/swtpm

RUN mk-build-deps \
    --install \
    --build-dep \
    '--tool=apt-get --no-install-recommends -y' \
    debian/control
RUN NOCONFIGURE=1 ./autogen.sh
RUN dpkg-buildpackage -b -us -uc -j$(nproc)
ENTRYPOINT tar --create --to-stdout /build/swtpm/*.deb